[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pcode_graph"
version = "1.1.0"
authors = [
  { name="Samuel Hangouët", email="samuel.hangouet@quarkslab.com" },
]
description = "Build, display and vectorize semantic graphs from binary code"
readme = "README.md"
requires-python = ">= 3.12"
dependencies = [
"keystone-engine~=0.9.2",
"loguru",
"pypcode>=4.0.0",
"pyvis",
"lief~=1.0.0",
"docopt"
]

license = "MIT"
license-files = ["LICENSE"]

classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Topic :: Security",
]

[project.urls]
Homepage = "https://github.com/quarkslab/pcode_graph"
Issues = "https://github.com/quarkslab/pcode_graph/issues"

[project.optional-dependencies]
torch = [
  "torch~=2.13.0",
  "torch_geometric~=2.8.0",
]
test = ["pytest", "pytest-timeout"]

[tool.hatch.build.targets.wheel]
packages = ["pcode_graph"]

[project.scripts]
cdg = "pcode_graph.cli:main"
