
from .arch import Arch

"""Exact register aliasing groups for pypcode / Ghidra SLEIGH.
Generated from the real SLEIGH register tables (pypcode 4.0.0)
ALIAS[arch][widest] == set of register names that share bits with `widest`.
"""

ALIAS: dict[Arch, dict[str, set[str]]] = {}

# x86_32 -- x86:LE:32:default (63 groupes)
ALIAS[Arch.x86_32] = {
    "BCST64": {"BCST16", "BCST32", "BCST4", "BCST8"},
    "BND0": {"BND0_LB", "BND0_UB"},
    "BND1": {"BND1_LB", "BND1_UB"},
    "BND2": {"BND2_LB", "BND2_UB"},
    "BND3": {"BND3_LB", "BND3_UB"},
    "EAX": {"AH", "AL", "AX"},
    "EBP": {"BP"},
    "EBX": {"BH", "BL", "BX"},
    "ECX": {"CH", "CL", "CX"},
    "EDI": {"DI"},
    "EDX": {"DH", "DL", "DX"},
    "EIP": {"IP"},
    "ESI": {"SI"},
    "ESP": {"SP"},
    "GDTR": {"GDTR_Address", "GDTR_Limit"},
    "IDTR": {"IDTR_Address", "IDTR_Limit"},
    "LDTR": {"LDTR_Address", "LDTR_Limit"},
    "ST0": {
        "MM0",
        "MM0_Ba",
        "MM0_Bb",
        "MM0_Bc",
        "MM0_Bd",
        "MM0_Be",
        "MM0_Bf",
        "MM0_Bg",
        "MM0_Bh",
        "MM0_Da",
        "MM0_Db",
        "MM0_Wa",
        "MM0_Wb",
        "MM0_Wc",
        "MM0_Wd",
        "ST0h",
    },
    "ST1": {
        "MM1",
        "MM1_Ba",
        "MM1_Bb",
        "MM1_Bc",
        "MM1_Bd",
        "MM1_Be",
        "MM1_Bf",
        "MM1_Bg",
        "MM1_Bh",
        "MM1_Da",
        "MM1_Db",
        "MM1_Wa",
        "MM1_Wb",
        "MM1_Wc",
        "MM1_Wd",
        "ST1h",
    },
    "ST2": {
        "MM2",
        "MM2_Ba",
        "MM2_Bb",
        "MM2_Bc",
        "MM2_Bd",
        "MM2_Be",
        "MM2_Bf",
        "MM2_Bg",
        "MM2_Bh",
        "MM2_Da",
        "MM2_Db",
        "MM2_Wa",
        "MM2_Wb",
        "MM2_Wc",
        "MM2_Wd",
        "ST2h",
    },
    "ST3": {
        "MM3",
        "MM3_Ba",
        "MM3_Bb",
        "MM3_Bc",
        "MM3_Bd",
        "MM3_Be",
        "MM3_Bf",
        "MM3_Bg",
        "MM3_Bh",
        "MM3_Da",
        "MM3_Db",
        "MM3_Wa",
        "MM3_Wb",
        "MM3_Wc",
        "MM3_Wd",
        "ST3h",
    },
    "ST4": {
        "MM4",
        "MM4_Ba",
        "MM4_Bb",
        "MM4_Bc",
        "MM4_Bd",
        "MM4_Be",
        "MM4_Bf",
        "MM4_Bg",
        "MM4_Bh",
        "MM4_Da",
        "MM4_Db",
        "MM4_Wa",
        "MM4_Wb",
        "MM4_Wc",
        "MM4_Wd",
        "ST4h",
    },
    "ST5": {
        "MM5",
        "MM5_Ba",
        "MM5_Bb",
        "MM5_Bc",
        "MM5_Bd",
        "MM5_Be",
        "MM5_Bf",
        "MM5_Bg",
        "MM5_Bh",
        "MM5_Da",
        "MM5_Db",
        "MM5_Wa",
        "MM5_Wb",
        "MM5_Wc",
        "MM5_Wd",
        "ST5h",
    },
    "ST6": {
        "MM6",
        "MM6_Ba",
        "MM6_Bb",
        "MM6_Bc",
        "MM6_Bd",
        "MM6_Be",
        "MM6_Bf",
        "MM6_Bg",
        "MM6_Bh",
        "MM6_Da",
        "MM6_Db",
        "MM6_Wa",
        "MM6_Wb",
        "MM6_Wc",
        "MM6_Wd",
        "ST6h",
    },
    "ST7": {
        "MM7",
        "MM7_Ba",
        "MM7_Bb",
        "MM7_Bc",
        "MM7_Bd",
        "MM7_Be",
        "MM7_Bf",
        "MM7_Bg",
        "MM7_Bh",
        "MM7_Da",
        "MM7_Db",
        "MM7_Wa",
        "MM7_Wb",
        "MM7_Wc",
        "MM7_Wd",
        "ST7h",
    },
    "TR": {"TR_Address", "TR_Limit"},
    "ZMM0": {
        "XMM0",
        "XMM0_Ba",
        "XMM0_Bb",
        "XMM0_Bc",
        "XMM0_Bd",
        "XMM0_Be",
        "XMM0_Bf",
        "XMM0_Bg",
        "XMM0_Bh",
        "XMM0_Bi",
        "XMM0_Bj",
        "XMM0_Bk",
        "XMM0_Bl",
        "XMM0_Bm",
        "XMM0_Bn",
        "XMM0_Bo",
        "XMM0_Bp",
        "XMM0_Da",
        "XMM0_Db",
        "XMM0_Dc",
        "XMM0_Dd",
        "XMM0_Qa",
        "XMM0_Qb",
        "XMM0_Wa",
        "XMM0_Wb",
        "XMM0_Wc",
        "XMM0_Wd",
        "XMM0_We",
        "XMM0_Wf",
        "XMM0_Wg",
        "XMM0_Wh",
        "YMM0",
        "YMM0_H",
    },
    "ZMM1": {
        "XMM1",
        "XMM1_Ba",
        "XMM1_Bb",
        "XMM1_Bc",
        "XMM1_Bd",
        "XMM1_Be",
        "XMM1_Bf",
        "XMM1_Bg",
        "XMM1_Bh",
        "XMM1_Bi",
        "XMM1_Bj",
        "XMM1_Bk",
        "XMM1_Bl",
        "XMM1_Bm",
        "XMM1_Bn",
        "XMM1_Bo",
        "XMM1_Bp",
        "XMM1_Da",
        "XMM1_Db",
        "XMM1_Dc",
        "XMM1_Dd",
        "XMM1_Qa",
        "XMM1_Qb",
        "XMM1_Wa",
        "XMM1_Wb",
        "XMM1_Wc",
        "XMM1_Wd",
        "XMM1_We",
        "XMM1_Wf",
        "XMM1_Wg",
        "XMM1_Wh",
        "YMM1",
        "YMM1_H",
    },
    "ZMM10": {
        "XMM10",
        "XMM10_Ba",
        "XMM10_Bb",
        "XMM10_Bc",
        "XMM10_Bd",
        "XMM10_Be",
        "XMM10_Bf",
        "XMM10_Bg",
        "XMM10_Bh",
        "XMM10_Bi",
        "XMM10_Bj",
        "XMM10_Bk",
        "XMM10_Bl",
        "XMM10_Bm",
        "XMM10_Bn",
        "XMM10_Bo",
        "XMM10_Bp",
        "XMM10_Da",
        "XMM10_Db",
        "XMM10_Dc",
        "XMM10_Dd",
        "XMM10_Qa",
        "XMM10_Qb",
        "XMM10_Wa",
        "XMM10_Wb",
        "XMM10_Wc",
        "XMM10_Wd",
        "XMM10_We",
        "XMM10_Wf",
        "XMM10_Wg",
        "XMM10_Wh",
        "YMM10",
        "YMM10_H",
    },
    "ZMM11": {
        "XMM11",
        "XMM11_Ba",
        "XMM11_Bb",
        "XMM11_Bc",
        "XMM11_Bd",
        "XMM11_Be",
        "XMM11_Bf",
        "XMM11_Bg",
        "XMM11_Bh",
        "XMM11_Bi",
        "XMM11_Bj",
        "XMM11_Bk",
        "XMM11_Bl",
        "XMM11_Bm",
        "XMM11_Bn",
        "XMM11_Bo",
        "XMM11_Bp",
        "XMM11_Da",
        "XMM11_Db",
        "XMM11_Dc",
        "XMM11_Dd",
        "XMM11_Qa",
        "XMM11_Qb",
        "XMM11_Wa",
        "XMM11_Wb",
        "XMM11_Wc",
        "XMM11_Wd",
        "XMM11_We",
        "XMM11_Wf",
        "XMM11_Wg",
        "XMM11_Wh",
        "YMM11",
        "YMM11_H",
    },
    "ZMM12": {
        "XMM12",
        "XMM12_Ba",
        "XMM12_Bb",
        "XMM12_Bc",
        "XMM12_Bd",
        "XMM12_Be",
        "XMM12_Bf",
        "XMM12_Bg",
        "XMM12_Bh",
        "XMM12_Bi",
        "XMM12_Bj",
        "XMM12_Bk",
        "XMM12_Bl",
        "XMM12_Bm",
        "XMM12_Bn",
        "XMM12_Bo",
        "XMM12_Bp",
        "XMM12_Da",
        "XMM12_Db",
        "XMM12_Dc",
        "XMM12_Dd",
        "XMM12_Qa",
        "XMM12_Qb",
        "XMM12_Wa",
        "XMM12_Wb",
        "XMM12_Wc",
        "XMM12_Wd",
        "XMM12_We",
        "XMM12_Wf",
        "XMM12_Wg",
        "XMM12_Wh",
        "YMM12",
        "YMM12_H",
    },
    "ZMM13": {
        "XMM13",
        "XMM13_Ba",
        "XMM13_Bb",
        "XMM13_Bc",
        "XMM13_Bd",
        "XMM13_Be",
        "XMM13_Bf",
        "XMM13_Bg",
        "XMM13_Bh",
        "XMM13_Bi",
        "XMM13_Bj",
        "XMM13_Bk",
        "XMM13_Bl",
        "XMM13_Bm",
        "XMM13_Bn",
        "XMM13_Bo",
        "XMM13_Bp",
        "XMM13_Da",
        "XMM13_Db",
        "XMM13_Dc",
        "XMM13_Dd",
        "XMM13_Qa",
        "XMM13_Qb",
        "XMM13_Wa",
        "XMM13_Wb",
        "XMM13_Wc",
        "XMM13_Wd",
        "XMM13_We",
        "XMM13_Wf",
        "XMM13_Wg",
        "XMM13_Wh",
        "YMM13",
        "YMM13_H",
    },
    "ZMM14": {
        "XMM14",
        "XMM14_Ba",
        "XMM14_Bb",
        "XMM14_Bc",
        "XMM14_Bd",
        "XMM14_Be",
        "XMM14_Bf",
        "XMM14_Bg",
        "XMM14_Bh",
        "XMM14_Bi",
        "XMM14_Bj",
        "XMM14_Bk",
        "XMM14_Bl",
        "XMM14_Bm",
        "XMM14_Bn",
        "XMM14_Bo",
        "XMM14_Bp",
        "XMM14_Da",
        "XMM14_Db",
        "XMM14_Dc",
        "XMM14_Dd",
        "XMM14_Qa",
        "XMM14_Qb",
        "XMM14_Wa",
        "XMM14_Wb",
        "XMM14_Wc",
        "XMM14_Wd",
        "XMM14_We",
        "XMM14_Wf",
        "XMM14_Wg",
        "XMM14_Wh",
        "YMM14",
        "YMM14_H",
    },
    "ZMM15": {
        "XMM15",
        "XMM15_Ba",
        "XMM15_Bb",
        "XMM15_Bc",
        "XMM15_Bd",
        "XMM15_Be",
        "XMM15_Bf",
        "XMM15_Bg",
        "XMM15_Bh",
        "XMM15_Bi",
        "XMM15_Bj",
        "XMM15_Bk",
        "XMM15_Bl",
        "XMM15_Bm",
        "XMM15_Bn",
        "XMM15_Bo",
        "XMM15_Bp",
        "XMM15_Da",
        "XMM15_Db",
        "XMM15_Dc",
        "XMM15_Dd",
        "XMM15_Qa",
        "XMM15_Qb",
        "XMM15_Wa",
        "XMM15_Wb",
        "XMM15_Wc",
        "XMM15_Wd",
        "XMM15_We",
        "XMM15_Wf",
        "XMM15_Wg",
        "XMM15_Wh",
        "YMM15",
        "YMM15_H",
    },
    "ZMM16": {
        "XMM16",
        "XMM16_Ba",
        "XMM16_Bb",
        "XMM16_Bc",
        "XMM16_Bd",
        "XMM16_Be",
        "XMM16_Bf",
        "XMM16_Bg",
        "XMM16_Bh",
        "XMM16_Bi",
        "XMM16_Bj",
        "XMM16_Bk",
        "XMM16_Bl",
        "XMM16_Bm",
        "XMM16_Bn",
        "XMM16_Bo",
        "XMM16_Bp",
        "XMM16_Da",
        "XMM16_Db",
        "XMM16_Dc",
        "XMM16_Dd",
        "XMM16_Qa",
        "XMM16_Qb",
        "XMM16_Wa",
        "XMM16_Wb",
        "XMM16_Wc",
        "XMM16_Wd",
        "XMM16_We",
        "XMM16_Wf",
        "XMM16_Wg",
        "XMM16_Wh",
        "YMM16",
        "YMM16_H",
    },
    "ZMM17": {
        "XMM17",
        "XMM17_Ba",
        "XMM17_Bb",
        "XMM17_Bc",
        "XMM17_Bd",
        "XMM17_Be",
        "XMM17_Bf",
        "XMM17_Bg",
        "XMM17_Bh",
        "XMM17_Bi",
        "XMM17_Bj",
        "XMM17_Bk",
        "XMM17_Bl",
        "XMM17_Bm",
        "XMM17_Bn",
        "XMM17_Bo",
        "XMM17_Bp",
        "XMM17_Da",
        "XMM17_Db",
        "XMM17_Dc",
        "XMM17_Dd",
        "XMM17_Qa",
        "XMM17_Qb",
        "XMM17_Wa",
        "XMM17_Wb",
        "XMM17_Wc",
        "XMM17_Wd",
        "XMM17_We",
        "XMM17_Wf",
        "XMM17_Wg",
        "XMM17_Wh",
        "YMM17",
        "YMM17_H",
    },
    "ZMM18": {
        "XMM18",
        "XMM18_Ba",
        "XMM18_Bb",
        "XMM18_Bc",
        "XMM18_Bd",
        "XMM18_Be",
        "XMM18_Bf",
        "XMM18_Bg",
        "XMM18_Bh",
        "XMM18_Bi",
        "XMM18_Bj",
        "XMM18_Bk",
        "XMM18_Bl",
        "XMM18_Bm",
        "XMM18_Bn",
        "XMM18_Bo",
        "XMM18_Bp",
        "XMM18_Da",
        "XMM18_Db",
        "XMM18_Dc",
        "XMM18_Dd",
        "XMM18_Qa",
        "XMM18_Qb",
        "XMM18_Wa",
        "XMM18_Wb",
        "XMM18_Wc",
        "XMM18_Wd",
        "XMM18_We",
        "XMM18_Wf",
        "XMM18_Wg",
        "XMM18_Wh",
        "YMM18",
        "YMM18_H",
    },
    "ZMM19": {
        "XMM19",
        "XMM19_Ba",
        "XMM19_Bb",
        "XMM19_Bc",
        "XMM19_Bd",
        "XMM19_Be",
        "XMM19_Bf",
        "XMM19_Bg",
        "XMM19_Bh",
        "XMM19_Bi",
        "XMM19_Bj",
        "XMM19_Bk",
        "XMM19_Bl",
        "XMM19_Bm",
        "XMM19_Bn",
        "XMM19_Bo",
        "XMM19_Bp",
        "XMM19_Da",
        "XMM19_Db",
        "XMM19_Dc",
        "XMM19_Dd",
        "XMM19_Qa",
        "XMM19_Qb",
        "XMM19_Wa",
        "XMM19_Wb",
        "XMM19_Wc",
        "XMM19_Wd",
        "XMM19_We",
        "XMM19_Wf",
        "XMM19_Wg",
        "XMM19_Wh",
        "YMM19",
        "YMM19_H",
    },
    "ZMM2": {
        "XMM2",
        "XMM2_Ba",
        "XMM2_Bb",
        "XMM2_Bc",
        "XMM2_Bd",
        "XMM2_Be",
        "XMM2_Bf",
        "XMM2_Bg",
        "XMM2_Bh",
        "XMM2_Bi",
        "XMM2_Bj",
        "XMM2_Bk",
        "XMM2_Bl",
        "XMM2_Bm",
        "XMM2_Bn",
        "XMM2_Bo",
        "XMM2_Bp",
        "XMM2_Da",
        "XMM2_Db",
        "XMM2_Dc",
        "XMM2_Dd",
        "XMM2_Qa",
        "XMM2_Qb",
        "XMM2_Wa",
        "XMM2_Wb",
        "XMM2_Wc",
        "XMM2_Wd",
        "XMM2_We",
        "XMM2_Wf",
        "XMM2_Wg",
        "XMM2_Wh",
        "YMM2",
        "YMM2_H",
    },
    "ZMM20": {
        "XMM20",
        "XMM20_Ba",
        "XMM20_Bb",
        "XMM20_Bc",
        "XMM20_Bd",
        "XMM20_Be",
        "XMM20_Bf",
        "XMM20_Bg",
        "XMM20_Bh",
        "XMM20_Bi",
        "XMM20_Bj",
        "XMM20_Bk",
        "XMM20_Bl",
        "XMM20_Bm",
        "XMM20_Bn",
        "XMM20_Bo",
        "XMM20_Bp",
        "XMM20_Da",
        "XMM20_Db",
        "XMM20_Dc",
        "XMM20_Dd",
        "XMM20_Qa",
        "XMM20_Qb",
        "XMM20_Wa",
        "XMM20_Wb",
        "XMM20_Wc",
        "XMM20_Wd",
        "XMM20_We",
        "XMM20_Wf",
        "XMM20_Wg",
        "XMM20_Wh",
        "YMM20",
        "YMM20_H",
    },
    "ZMM21": {
        "XMM21",
        "XMM21_Ba",
        "XMM21_Bb",
        "XMM21_Bc",
        "XMM21_Bd",
        "XMM21_Be",
        "XMM21_Bf",
        "XMM21_Bg",
        "XMM21_Bh",
        "XMM21_Bi",
        "XMM21_Bj",
        "XMM21_Bk",
        "XMM21_Bl",
        "XMM21_Bm",
        "XMM21_Bn",
        "XMM21_Bo",
        "XMM21_Bp",
        "XMM21_Da",
        "XMM21_Db",
        "XMM21_Dc",
        "XMM21_Dd",
        "XMM21_Qa",
        "XMM21_Qb",
        "XMM21_Wa",
        "XMM21_Wb",
        "XMM21_Wc",
        "XMM21_Wd",
        "XMM21_We",
        "XMM21_Wf",
        "XMM21_Wg",
        "XMM21_Wh",
        "YMM21",
        "YMM21_H",
    },
    "ZMM22": {
        "XMM22",
        "XMM22_Ba",
        "XMM22_Bb",
        "XMM22_Bc",
        "XMM22_Bd",
        "XMM22_Be",
        "XMM22_Bf",
        "XMM22_Bg",
        "XMM22_Bh",
        "XMM22_Bi",
        "XMM22_Bj",
        "XMM22_Bk",
        "XMM22_Bl",
        "XMM22_Bm",
        "XMM22_Bn",
        "XMM22_Bo",
        "XMM22_Bp",
        "XMM22_Da",
        "XMM22_Db",
        "XMM22_Dc",
        "XMM22_Dd",
        "XMM22_Qa",
        "XMM22_Qb",
        "XMM22_Wa",
        "XMM22_Wb",
        "XMM22_Wc",
        "XMM22_Wd",
        "XMM22_We",
        "XMM22_Wf",
        "XMM22_Wg",
        "XMM22_Wh",
        "YMM22",
        "YMM22_H",
    },
    "ZMM23": {
        "XMM23",
        "XMM23_Ba",
        "XMM23_Bb",
        "XMM23_Bc",
        "XMM23_Bd",
        "XMM23_Be",
        "XMM23_Bf",
        "XMM23_Bg",
        "XMM23_Bh",
        "XMM23_Bi",
        "XMM23_Bj",
        "XMM23_Bk",
        "XMM23_Bl",
        "XMM23_Bm",
        "XMM23_Bn",
        "XMM23_Bo",
        "XMM23_Bp",
        "XMM23_Da",
        "XMM23_Db",
        "XMM23_Dc",
        "XMM23_Dd",
        "XMM23_Qa",
        "XMM23_Qb",
        "XMM23_Wa",
        "XMM23_Wb",
        "XMM23_Wc",
        "XMM23_Wd",
        "XMM23_We",
        "XMM23_Wf",
        "XMM23_Wg",
        "XMM23_Wh",
        "YMM23",
        "YMM23_H",
    },
    "ZMM24": {
        "XMM24",
        "XMM24_Ba",
        "XMM24_Bb",
        "XMM24_Bc",
        "XMM24_Bd",
        "XMM24_Be",
        "XMM24_Bf",
        "XMM24_Bg",
        "XMM24_Bh",
        "XMM24_Bi",
        "XMM24_Bj",
        "XMM24_Bk",
        "XMM24_Bl",
        "XMM24_Bm",
        "XMM24_Bn",
        "XMM24_Bo",
        "XMM24_Bp",
        "XMM24_Da",
        "XMM24_Db",
        "XMM24_Dc",
        "XMM24_Dd",
        "XMM24_Qa",
        "XMM24_Qb",
        "XMM24_Wa",
        "XMM24_Wb",
        "XMM24_Wc",
        "XMM24_Wd",
        "XMM24_We",
        "XMM24_Wf",
        "XMM24_Wg",
        "XMM24_Wh",
        "YMM24",
        "YMM24_H",
    },
    "ZMM25": {
        "XMM25",
        "XMM25_Ba",
        "XMM25_Bb",
        "XMM25_Bc",
        "XMM25_Bd",
        "XMM25_Be",
        "XMM25_Bf",
        "XMM25_Bg",
        "XMM25_Bh",
        "XMM25_Bi",
        "XMM25_Bj",
        "XMM25_Bk",
        "XMM25_Bl",
        "XMM25_Bm",
        "XMM25_Bn",
        "XMM25_Bo",
        "XMM25_Bp",
        "XMM25_Da",
        "XMM25_Db",
        "XMM25_Dc",
        "XMM25_Dd",
        "XMM25_Qa",
        "XMM25_Qb",
        "XMM25_Wa",
        "XMM25_Wb",
        "XMM25_Wc",
        "XMM25_Wd",
        "XMM25_We",
        "XMM25_Wf",
        "XMM25_Wg",
        "XMM25_Wh",
        "YMM25",
        "YMM25_H",
    },
    "ZMM26": {
        "XMM26",
        "XMM26_Ba",
        "XMM26_Bb",
        "XMM26_Bc",
        "XMM26_Bd",
        "XMM26_Be",
        "XMM26_Bf",
        "XMM26_Bg",
        "XMM26_Bh",
        "XMM26_Bi",
        "XMM26_Bj",
        "XMM26_Bk",
        "XMM26_Bl",
        "XMM26_Bm",
        "XMM26_Bn",
        "XMM26_Bo",
        "XMM26_Bp",
        "XMM26_Da",
        "XMM26_Db",
        "XMM26_Dc",
        "XMM26_Dd",
        "XMM26_Qa",
        "XMM26_Qb",
        "XMM26_Wa",
        "XMM26_Wb",
        "XMM26_Wc",
        "XMM26_Wd",
        "XMM26_We",
        "XMM26_Wf",
        "XMM26_Wg",
        "XMM26_Wh",
        "YMM26",
        "YMM26_H",
    },
    "ZMM27": {
        "XMM27",
        "XMM27_Ba",
        "XMM27_Bb",
        "XMM27_Bc",
        "XMM27_Bd",
        "XMM27_Be",
        "XMM27_Bf",
        "XMM27_Bg",
        "XMM27_Bh",
        "XMM27_Bi",
        "XMM27_Bj",
        "XMM27_Bk",
        "XMM27_Bl",
        "XMM27_Bm",
        "XMM27_Bn",
        "XMM27_Bo",
        "XMM27_Bp",
        "XMM27_Da",
        "XMM27_Db",
        "XMM27_Dc",
        "XMM27_Dd",
        "XMM27_Qa",
        "XMM27_Qb",
        "XMM27_Wa",
        "XMM27_Wb",
        "XMM27_Wc",
        "XMM27_Wd",
        "XMM27_We",
        "XMM27_Wf",
        "XMM27_Wg",
        "XMM27_Wh",
        "YMM27",
        "YMM27_H",
    },
    "ZMM28": {
        "XMM28",
        "XMM28_Ba",
        "XMM28_Bb",
        "XMM28_Bc",
        "XMM28_Bd",
        "XMM28_Be",
        "XMM28_Bf",
        "XMM28_Bg",
        "XMM28_Bh",
        "XMM28_Bi",
        "XMM28_Bj",
        "XMM28_Bk",
        "XMM28_Bl",
        "XMM28_Bm",
        "XMM28_Bn",
        "XMM28_Bo",
        "XMM28_Bp",
        "XMM28_Da",
        "XMM28_Db",
        "XMM28_Dc",
        "XMM28_Dd",
        "XMM28_Qa",
        "XMM28_Qb",
        "XMM28_Wa",
        "XMM28_Wb",
        "XMM28_Wc",
        "XMM28_Wd",
        "XMM28_We",
        "XMM28_Wf",
        "XMM28_Wg",
        "XMM28_Wh",
        "YMM28",
        "YMM28_H",
    },
    "ZMM29": {
        "XMM29",
        "XMM29_Ba",
        "XMM29_Bb",
        "XMM29_Bc",
        "XMM29_Bd",
        "XMM29_Be",
        "XMM29_Bf",
        "XMM29_Bg",
        "XMM29_Bh",
        "XMM29_Bi",
        "XMM29_Bj",
        "XMM29_Bk",
        "XMM29_Bl",
        "XMM29_Bm",
        "XMM29_Bn",
        "XMM29_Bo",
        "XMM29_Bp",
        "XMM29_Da",
        "XMM29_Db",
        "XMM29_Dc",
        "XMM29_Dd",
        "XMM29_Qa",
        "XMM29_Qb",
        "XMM29_Wa",
        "XMM29_Wb",
        "XMM29_Wc",
        "XMM29_Wd",
        "XMM29_We",
        "XMM29_Wf",
        "XMM29_Wg",
        "XMM29_Wh",
        "YMM29",
        "YMM29_H",
    },
    "ZMM3": {
        "XMM3",
        "XMM3_Ba",
        "XMM3_Bb",
        "XMM3_Bc",
        "XMM3_Bd",
        "XMM3_Be",
        "XMM3_Bf",
        "XMM3_Bg",
        "XMM3_Bh",
        "XMM3_Bi",
        "XMM3_Bj",
        "XMM3_Bk",
        "XMM3_Bl",
        "XMM3_Bm",
        "XMM3_Bn",
        "XMM3_Bo",
        "XMM3_Bp",
        "XMM3_Da",
        "XMM3_Db",
        "XMM3_Dc",
        "XMM3_Dd",
        "XMM3_Qa",
        "XMM3_Qb",
        "XMM3_Wa",
        "XMM3_Wb",
        "XMM3_Wc",
        "XMM3_Wd",
        "XMM3_We",
        "XMM3_Wf",
        "XMM3_Wg",
        "XMM3_Wh",
        "YMM3",
        "YMM3_H",
    },
    "ZMM30": {
        "XMM30",
        "XMM30_Ba",
        "XMM30_Bb",
        "XMM30_Bc",
        "XMM30_Bd",
        "XMM30_Be",
        "XMM30_Bf",
        "XMM30_Bg",
        "XMM30_Bh",
        "XMM30_Bi",
        "XMM30_Bj",
        "XMM30_Bk",
        "XMM30_Bl",
        "XMM30_Bm",
        "XMM30_Bn",
        "XMM30_Bo",
        "XMM30_Bp",
        "XMM30_Da",
        "XMM30_Db",
        "XMM30_Dc",
        "XMM30_Dd",
        "XMM30_Qa",
        "XMM30_Qb",
        "XMM30_Wa",
        "XMM30_Wb",
        "XMM30_Wc",
        "XMM30_Wd",
        "XMM30_We",
        "XMM30_Wf",
        "XMM30_Wg",
        "XMM30_Wh",
        "YMM30",
        "YMM30_H",
    },
    "ZMM31": {
        "XMM31",
        "XMM31_Ba",
        "XMM31_Bb",
        "XMM31_Bc",
        "XMM31_Bd",
        "XMM31_Be",
        "XMM31_Bf",
        "XMM31_Bg",
        "XMM31_Bh",
        "XMM31_Bi",
        "XMM31_Bj",
        "XMM31_Bk",
        "XMM31_Bl",
        "XMM31_Bm",
        "XMM31_Bn",
        "XMM31_Bo",
        "XMM31_Bp",
        "XMM31_Da",
        "XMM31_Db",
        "XMM31_Dc",
        "XMM31_Dd",
        "XMM31_Qa",
        "XMM31_Qb",
        "XMM31_Wa",
        "XMM31_Wb",
        "XMM31_Wc",
        "XMM31_Wd",
        "XMM31_We",
        "XMM31_Wf",
        "XMM31_Wg",
        "XMM31_Wh",
        "YMM31",
        "YMM31_H",
    },
    "ZMM4": {
        "XMM4",
        "XMM4_Ba",
        "XMM4_Bb",
        "XMM4_Bc",
        "XMM4_Bd",
        "XMM4_Be",
        "XMM4_Bf",
        "XMM4_Bg",
        "XMM4_Bh",
        "XMM4_Bi",
        "XMM4_Bj",
        "XMM4_Bk",
        "XMM4_Bl",
        "XMM4_Bm",
        "XMM4_Bn",
        "XMM4_Bo",
        "XMM4_Bp",
        "XMM4_Da",
        "XMM4_Db",
        "XMM4_Dc",
        "XMM4_Dd",
        "XMM4_Qa",
        "XMM4_Qb",
        "XMM4_Wa",
        "XMM4_Wb",
        "XMM4_Wc",
        "XMM4_Wd",
        "XMM4_We",
        "XMM4_Wf",
        "XMM4_Wg",
        "XMM4_Wh",
        "YMM4",
        "YMM4_H",
    },
    "ZMM5": {
        "XMM5",
        "XMM5_Ba",
        "XMM5_Bb",
        "XMM5_Bc",
        "XMM5_Bd",
        "XMM5_Be",
        "XMM5_Bf",
        "XMM5_Bg",
        "XMM5_Bh",
        "XMM5_Bi",
        "XMM5_Bj",
        "XMM5_Bk",
        "XMM5_Bl",
        "XMM5_Bm",
        "XMM5_Bn",
        "XMM5_Bo",
        "XMM5_Bp",
        "XMM5_Da",
        "XMM5_Db",
        "XMM5_Dc",
        "XMM5_Dd",
        "XMM5_Qa",
        "XMM5_Qb",
        "XMM5_Wa",
        "XMM5_Wb",
        "XMM5_Wc",
        "XMM5_Wd",
        "XMM5_We",
        "XMM5_Wf",
        "XMM5_Wg",
        "XMM5_Wh",
        "YMM5",
        "YMM5_H",
    },
    "ZMM6": {
        "XMM6",
        "XMM6_Ba",
        "XMM6_Bb",
        "XMM6_Bc",
        "XMM6_Bd",
        "XMM6_Be",
        "XMM6_Bf",
        "XMM6_Bg",
        "XMM6_Bh",
        "XMM6_Bi",
        "XMM6_Bj",
        "XMM6_Bk",
        "XMM6_Bl",
        "XMM6_Bm",
        "XMM6_Bn",
        "XMM6_Bo",
        "XMM6_Bp",
        "XMM6_Da",
        "XMM6_Db",
        "XMM6_Dc",
        "XMM6_Dd",
        "XMM6_Qa",
        "XMM6_Qb",
        "XMM6_Wa",
        "XMM6_Wb",
        "XMM6_Wc",
        "XMM6_Wd",
        "XMM6_We",
        "XMM6_Wf",
        "XMM6_Wg",
        "XMM6_Wh",
        "YMM6",
        "YMM6_H",
    },
    "ZMM7": {
        "XMM7",
        "XMM7_Ba",
        "XMM7_Bb",
        "XMM7_Bc",
        "XMM7_Bd",
        "XMM7_Be",
        "XMM7_Bf",
        "XMM7_Bg",
        "XMM7_Bh",
        "XMM7_Bi",
        "XMM7_Bj",
        "XMM7_Bk",
        "XMM7_Bl",
        "XMM7_Bm",
        "XMM7_Bn",
        "XMM7_Bo",
        "XMM7_Bp",
        "XMM7_Da",
        "XMM7_Db",
        "XMM7_Dc",
        "XMM7_Dd",
        "XMM7_Qa",
        "XMM7_Qb",
        "XMM7_Wa",
        "XMM7_Wb",
        "XMM7_Wc",
        "XMM7_Wd",
        "XMM7_We",
        "XMM7_Wf",
        "XMM7_Wg",
        "XMM7_Wh",
        "YMM7",
        "YMM7_H",
    },
    "ZMM8": {
        "XMM8",
        "XMM8_Ba",
        "XMM8_Bb",
        "XMM8_Bc",
        "XMM8_Bd",
        "XMM8_Be",
        "XMM8_Bf",
        "XMM8_Bg",
        "XMM8_Bh",
        "XMM8_Bi",
        "XMM8_Bj",
        "XMM8_Bk",
        "XMM8_Bl",
        "XMM8_Bm",
        "XMM8_Bn",
        "XMM8_Bo",
        "XMM8_Bp",
        "XMM8_Da",
        "XMM8_Db",
        "XMM8_Dc",
        "XMM8_Dd",
        "XMM8_Qa",
        "XMM8_Qb",
        "XMM8_Wa",
        "XMM8_Wb",
        "XMM8_Wc",
        "XMM8_Wd",
        "XMM8_We",
        "XMM8_Wf",
        "XMM8_Wg",
        "XMM8_Wh",
        "YMM8",
        "YMM8_H",
    },
    "ZMM9": {
        "XMM9",
        "XMM9_Ba",
        "XMM9_Bb",
        "XMM9_Bc",
        "XMM9_Bd",
        "XMM9_Be",
        "XMM9_Bf",
        "XMM9_Bg",
        "XMM9_Bh",
        "XMM9_Bi",
        "XMM9_Bj",
        "XMM9_Bk",
        "XMM9_Bl",
        "XMM9_Bm",
        "XMM9_Bn",
        "XMM9_Bo",
        "XMM9_Bp",
        "XMM9_Da",
        "XMM9_Db",
        "XMM9_Dc",
        "XMM9_Dd",
        "XMM9_Qa",
        "XMM9_Qb",
        "XMM9_Wa",
        "XMM9_Wb",
        "XMM9_Wc",
        "XMM9_Wd",
        "XMM9_We",
        "XMM9_Wf",
        "XMM9_Wg",
        "XMM9_Wh",
        "YMM9",
        "YMM9_H",
    },
    "ZmmMask": {"XmmMask", "YmmMask"},
    "ZmmResult": {"XmmResult", "YmmResult"},
    "eflags": {"flags"},
    "xmmTmp1": {
        "xmmTmp1_Da",
        "xmmTmp1_Db",
        "xmmTmp1_Dc",
        "xmmTmp1_Dd",
        "xmmTmp1_Qa",
        "xmmTmp1_Qb",
    },
    "xmmTmp2": {
        "xmmTmp2_Da",
        "xmmTmp2_Db",
        "xmmTmp2_Dc",
        "xmmTmp2_Dd",
        "xmmTmp2_Qa",
        "xmmTmp2_Qb",
    },
}

# x86_64 -- x86:LE:64:default (71 groupes)
ALIAS[Arch.x86_64] = {
    "BCST64": {"BCST16", "BCST32", "BCST4", "BCST8"},
    "BND0": {"BND0_LB", "BND0_UB"},
    "BND1": {"BND1_LB", "BND1_UB"},
    "BND2": {"BND2_LB", "BND2_UB"},
    "BND3": {"BND3_LB", "BND3_UB"},
    "GDTR": {"GDTR_Address", "GDTR_Limit"},
    "IDTR": {"IDTR_Address", "IDTR_Limit"},
    "LDTR": {"LDTR_Address", "LDTR_Attributes", "LDTR_Limit"},
    "R10": {"R10B", "R10D", "R10W"},
    "R11": {"R11B", "R11D", "R11W"},
    "R12": {"R12B", "R12D", "R12W"},
    "R13": {"R13B", "R13D", "R13W"},
    "R14": {"R14B", "R14D", "R14W"},
    "R15": {"R15B", "R15D", "R15W"},
    "R8": {"R8B", "R8D", "R8W"},
    "R9": {"R9B", "R9D", "R9W"},
    "RAX": {"AH", "AL", "AX", "EAX"},
    "RBP": {"BP", "BPL", "EBP"},
    "RBX": {"BH", "BL", "BX", "EBX"},
    "RCX": {"CH", "CL", "CX", "ECX"},
    "RDI": {"DI", "DIL", "EDI"},
    "RDX": {"DH", "DL", "DX", "EDX"},
    "RIP": {"EIP", "IP"},
    "RSI": {"ESI", "SI", "SIL"},
    "RSP": {"ESP", "SP", "SPL"},
    "ST0": {
        "MM0",
        "MM0_Ba",
        "MM0_Bb",
        "MM0_Bc",
        "MM0_Bd",
        "MM0_Be",
        "MM0_Bf",
        "MM0_Bg",
        "MM0_Bh",
        "MM0_Da",
        "MM0_Db",
        "MM0_Wa",
        "MM0_Wb",
        "MM0_Wc",
        "MM0_Wd",
        "ST0h",
    },
    "ST1": {
        "MM1",
        "MM1_Ba",
        "MM1_Bb",
        "MM1_Bc",
        "MM1_Bd",
        "MM1_Be",
        "MM1_Bf",
        "MM1_Bg",
        "MM1_Bh",
        "MM1_Da",
        "MM1_Db",
        "MM1_Wa",
        "MM1_Wb",
        "MM1_Wc",
        "MM1_Wd",
        "ST1h",
    },
    "ST2": {
        "MM2",
        "MM2_Ba",
        "MM2_Bb",
        "MM2_Bc",
        "MM2_Bd",
        "MM2_Be",
        "MM2_Bf",
        "MM2_Bg",
        "MM2_Bh",
        "MM2_Da",
        "MM2_Db",
        "MM2_Wa",
        "MM2_Wb",
        "MM2_Wc",
        "MM2_Wd",
        "ST2h",
    },
    "ST3": {
        "MM3",
        "MM3_Ba",
        "MM3_Bb",
        "MM3_Bc",
        "MM3_Bd",
        "MM3_Be",
        "MM3_Bf",
        "MM3_Bg",
        "MM3_Bh",
        "MM3_Da",
        "MM3_Db",
        "MM3_Wa",
        "MM3_Wb",
        "MM3_Wc",
        "MM3_Wd",
        "ST3h",
    },
    "ST4": {
        "MM4",
        "MM4_Ba",
        "MM4_Bb",
        "MM4_Bc",
        "MM4_Bd",
        "MM4_Be",
        "MM4_Bf",
        "MM4_Bg",
        "MM4_Bh",
        "MM4_Da",
        "MM4_Db",
        "MM4_Wa",
        "MM4_Wb",
        "MM4_Wc",
        "MM4_Wd",
        "ST4h",
    },
    "ST5": {
        "MM5",
        "MM5_Ba",
        "MM5_Bb",
        "MM5_Bc",
        "MM5_Bd",
        "MM5_Be",
        "MM5_Bf",
        "MM5_Bg",
        "MM5_Bh",
        "MM5_Da",
        "MM5_Db",
        "MM5_Wa",
        "MM5_Wb",
        "MM5_Wc",
        "MM5_Wd",
        "ST5h",
    },
    "ST6": {
        "MM6",
        "MM6_Ba",
        "MM6_Bb",
        "MM6_Bc",
        "MM6_Bd",
        "MM6_Be",
        "MM6_Bf",
        "MM6_Bg",
        "MM6_Bh",
        "MM6_Da",
        "MM6_Db",
        "MM6_Wa",
        "MM6_Wb",
        "MM6_Wc",
        "MM6_Wd",
        "ST6h",
    },
    "ST7": {
        "MM7",
        "MM7_Ba",
        "MM7_Bb",
        "MM7_Bc",
        "MM7_Bd",
        "MM7_Be",
        "MM7_Bf",
        "MM7_Bg",
        "MM7_Bh",
        "MM7_Da",
        "MM7_Db",
        "MM7_Wa",
        "MM7_Wb",
        "MM7_Wc",
        "MM7_Wd",
        "ST7h",
    },
    "TR": {"TR_Address", "TR_Attributes", "TR_Limit"},
    "ZMM0": {
        "XMM0",
        "XMM0_Ba",
        "XMM0_Bb",
        "XMM0_Bc",
        "XMM0_Bd",
        "XMM0_Be",
        "XMM0_Bf",
        "XMM0_Bg",
        "XMM0_Bh",
        "XMM0_Bi",
        "XMM0_Bj",
        "XMM0_Bk",
        "XMM0_Bl",
        "XMM0_Bm",
        "XMM0_Bn",
        "XMM0_Bo",
        "XMM0_Bp",
        "XMM0_Da",
        "XMM0_Db",
        "XMM0_Dc",
        "XMM0_Dd",
        "XMM0_Qa",
        "XMM0_Qb",
        "XMM0_Wa",
        "XMM0_Wb",
        "XMM0_Wc",
        "XMM0_Wd",
        "XMM0_We",
        "XMM0_Wf",
        "XMM0_Wg",
        "XMM0_Wh",
        "YMM0",
        "YMM0_H",
    },
    "ZMM1": {
        "XMM1",
        "XMM1_Ba",
        "XMM1_Bb",
        "XMM1_Bc",
        "XMM1_Bd",
        "XMM1_Be",
        "XMM1_Bf",
        "XMM1_Bg",
        "XMM1_Bh",
        "XMM1_Bi",
        "XMM1_Bj",
        "XMM1_Bk",
        "XMM1_Bl",
        "XMM1_Bm",
        "XMM1_Bn",
        "XMM1_Bo",
        "XMM1_Bp",
        "XMM1_Da",
        "XMM1_Db",
        "XMM1_Dc",
        "XMM1_Dd",
        "XMM1_Qa",
        "XMM1_Qb",
        "XMM1_Wa",
        "XMM1_Wb",
        "XMM1_Wc",
        "XMM1_Wd",
        "XMM1_We",
        "XMM1_Wf",
        "XMM1_Wg",
        "XMM1_Wh",
        "YMM1",
        "YMM1_H",
    },
    "ZMM10": {
        "XMM10",
        "XMM10_Ba",
        "XMM10_Bb",
        "XMM10_Bc",
        "XMM10_Bd",
        "XMM10_Be",
        "XMM10_Bf",
        "XMM10_Bg",
        "XMM10_Bh",
        "XMM10_Bi",
        "XMM10_Bj",
        "XMM10_Bk",
        "XMM10_Bl",
        "XMM10_Bm",
        "XMM10_Bn",
        "XMM10_Bo",
        "XMM10_Bp",
        "XMM10_Da",
        "XMM10_Db",
        "XMM10_Dc",
        "XMM10_Dd",
        "XMM10_Qa",
        "XMM10_Qb",
        "XMM10_Wa",
        "XMM10_Wb",
        "XMM10_Wc",
        "XMM10_Wd",
        "XMM10_We",
        "XMM10_Wf",
        "XMM10_Wg",
        "XMM10_Wh",
        "YMM10",
        "YMM10_H",
    },
    "ZMM11": {
        "XMM11",
        "XMM11_Ba",
        "XMM11_Bb",
        "XMM11_Bc",
        "XMM11_Bd",
        "XMM11_Be",
        "XMM11_Bf",
        "XMM11_Bg",
        "XMM11_Bh",
        "XMM11_Bi",
        "XMM11_Bj",
        "XMM11_Bk",
        "XMM11_Bl",
        "XMM11_Bm",
        "XMM11_Bn",
        "XMM11_Bo",
        "XMM11_Bp",
        "XMM11_Da",
        "XMM11_Db",
        "XMM11_Dc",
        "XMM11_Dd",
        "XMM11_Qa",
        "XMM11_Qb",
        "XMM11_Wa",
        "XMM11_Wb",
        "XMM11_Wc",
        "XMM11_Wd",
        "XMM11_We",
        "XMM11_Wf",
        "XMM11_Wg",
        "XMM11_Wh",
        "YMM11",
        "YMM11_H",
    },
    "ZMM12": {
        "XMM12",
        "XMM12_Ba",
        "XMM12_Bb",
        "XMM12_Bc",
        "XMM12_Bd",
        "XMM12_Be",
        "XMM12_Bf",
        "XMM12_Bg",
        "XMM12_Bh",
        "XMM12_Bi",
        "XMM12_Bj",
        "XMM12_Bk",
        "XMM12_Bl",
        "XMM12_Bm",
        "XMM12_Bn",
        "XMM12_Bo",
        "XMM12_Bp",
        "XMM12_Da",
        "XMM12_Db",
        "XMM12_Dc",
        "XMM12_Dd",
        "XMM12_Qa",
        "XMM12_Qb",
        "XMM12_Wa",
        "XMM12_Wb",
        "XMM12_Wc",
        "XMM12_Wd",
        "XMM12_We",
        "XMM12_Wf",
        "XMM12_Wg",
        "XMM12_Wh",
        "YMM12",
        "YMM12_H",
    },
    "ZMM13": {
        "XMM13",
        "XMM13_Ba",
        "XMM13_Bb",
        "XMM13_Bc",
        "XMM13_Bd",
        "XMM13_Be",
        "XMM13_Bf",
        "XMM13_Bg",
        "XMM13_Bh",
        "XMM13_Bi",
        "XMM13_Bj",
        "XMM13_Bk",
        "XMM13_Bl",
        "XMM13_Bm",
        "XMM13_Bn",
        "XMM13_Bo",
        "XMM13_Bp",
        "XMM13_Da",
        "XMM13_Db",
        "XMM13_Dc",
        "XMM13_Dd",
        "XMM13_Qa",
        "XMM13_Qb",
        "XMM13_Wa",
        "XMM13_Wb",
        "XMM13_Wc",
        "XMM13_Wd",
        "XMM13_We",
        "XMM13_Wf",
        "XMM13_Wg",
        "XMM13_Wh",
        "YMM13",
        "YMM13_H",
    },
    "ZMM14": {
        "XMM14",
        "XMM14_Ba",
        "XMM14_Bb",
        "XMM14_Bc",
        "XMM14_Bd",
        "XMM14_Be",
        "XMM14_Bf",
        "XMM14_Bg",
        "XMM14_Bh",
        "XMM14_Bi",
        "XMM14_Bj",
        "XMM14_Bk",
        "XMM14_Bl",
        "XMM14_Bm",
        "XMM14_Bn",
        "XMM14_Bo",
        "XMM14_Bp",
        "XMM14_Da",
        "XMM14_Db",
        "XMM14_Dc",
        "XMM14_Dd",
        "XMM14_Qa",
        "XMM14_Qb",
        "XMM14_Wa",
        "XMM14_Wb",
        "XMM14_Wc",
        "XMM14_Wd",
        "XMM14_We",
        "XMM14_Wf",
        "XMM14_Wg",
        "XMM14_Wh",
        "YMM14",
        "YMM14_H",
    },
    "ZMM15": {
        "XMM15",
        "XMM15_Ba",
        "XMM15_Bb",
        "XMM15_Bc",
        "XMM15_Bd",
        "XMM15_Be",
        "XMM15_Bf",
        "XMM15_Bg",
        "XMM15_Bh",
        "XMM15_Bi",
        "XMM15_Bj",
        "XMM15_Bk",
        "XMM15_Bl",
        "XMM15_Bm",
        "XMM15_Bn",
        "XMM15_Bo",
        "XMM15_Bp",
        "XMM15_Da",
        "XMM15_Db",
        "XMM15_Dc",
        "XMM15_Dd",
        "XMM15_Qa",
        "XMM15_Qb",
        "XMM15_Wa",
        "XMM15_Wb",
        "XMM15_Wc",
        "XMM15_Wd",
        "XMM15_We",
        "XMM15_Wf",
        "XMM15_Wg",
        "XMM15_Wh",
        "YMM15",
        "YMM15_H",
    },
    "ZMM16": {
        "XMM16",
        "XMM16_Ba",
        "XMM16_Bb",
        "XMM16_Bc",
        "XMM16_Bd",
        "XMM16_Be",
        "XMM16_Bf",
        "XMM16_Bg",
        "XMM16_Bh",
        "XMM16_Bi",
        "XMM16_Bj",
        "XMM16_Bk",
        "XMM16_Bl",
        "XMM16_Bm",
        "XMM16_Bn",
        "XMM16_Bo",
        "XMM16_Bp",
        "XMM16_Da",
        "XMM16_Db",
        "XMM16_Dc",
        "XMM16_Dd",
        "XMM16_Qa",
        "XMM16_Qb",
        "XMM16_Wa",
        "XMM16_Wb",
        "XMM16_Wc",
        "XMM16_Wd",
        "XMM16_We",
        "XMM16_Wf",
        "XMM16_Wg",
        "XMM16_Wh",
        "YMM16",
        "YMM16_H",
    },
    "ZMM17": {
        "XMM17",
        "XMM17_Ba",
        "XMM17_Bb",
        "XMM17_Bc",
        "XMM17_Bd",
        "XMM17_Be",
        "XMM17_Bf",
        "XMM17_Bg",
        "XMM17_Bh",
        "XMM17_Bi",
        "XMM17_Bj",
        "XMM17_Bk",
        "XMM17_Bl",
        "XMM17_Bm",
        "XMM17_Bn",
        "XMM17_Bo",
        "XMM17_Bp",
        "XMM17_Da",
        "XMM17_Db",
        "XMM17_Dc",
        "XMM17_Dd",
        "XMM17_Qa",
        "XMM17_Qb",
        "XMM17_Wa",
        "XMM17_Wb",
        "XMM17_Wc",
        "XMM17_Wd",
        "XMM17_We",
        "XMM17_Wf",
        "XMM17_Wg",
        "XMM17_Wh",
        "YMM17",
        "YMM17_H",
    },
    "ZMM18": {
        "XMM18",
        "XMM18_Ba",
        "XMM18_Bb",
        "XMM18_Bc",
        "XMM18_Bd",
        "XMM18_Be",
        "XMM18_Bf",
        "XMM18_Bg",
        "XMM18_Bh",
        "XMM18_Bi",
        "XMM18_Bj",
        "XMM18_Bk",
        "XMM18_Bl",
        "XMM18_Bm",
        "XMM18_Bn",
        "XMM18_Bo",
        "XMM18_Bp",
        "XMM18_Da",
        "XMM18_Db",
        "XMM18_Dc",
        "XMM18_Dd",
        "XMM18_Qa",
        "XMM18_Qb",
        "XMM18_Wa",
        "XMM18_Wb",
        "XMM18_Wc",
        "XMM18_Wd",
        "XMM18_We",
        "XMM18_Wf",
        "XMM18_Wg",
        "XMM18_Wh",
        "YMM18",
        "YMM18_H",
    },
    "ZMM19": {
        "XMM19",
        "XMM19_Ba",
        "XMM19_Bb",
        "XMM19_Bc",
        "XMM19_Bd",
        "XMM19_Be",
        "XMM19_Bf",
        "XMM19_Bg",
        "XMM19_Bh",
        "XMM19_Bi",
        "XMM19_Bj",
        "XMM19_Bk",
        "XMM19_Bl",
        "XMM19_Bm",
        "XMM19_Bn",
        "XMM19_Bo",
        "XMM19_Bp",
        "XMM19_Da",
        "XMM19_Db",
        "XMM19_Dc",
        "XMM19_Dd",
        "XMM19_Qa",
        "XMM19_Qb",
        "XMM19_Wa",
        "XMM19_Wb",
        "XMM19_Wc",
        "XMM19_Wd",
        "XMM19_We",
        "XMM19_Wf",
        "XMM19_Wg",
        "XMM19_Wh",
        "YMM19",
        "YMM19_H",
    },
    "ZMM2": {
        "XMM2",
        "XMM2_Ba",
        "XMM2_Bb",
        "XMM2_Bc",
        "XMM2_Bd",
        "XMM2_Be",
        "XMM2_Bf",
        "XMM2_Bg",
        "XMM2_Bh",
        "XMM2_Bi",
        "XMM2_Bj",
        "XMM2_Bk",
        "XMM2_Bl",
        "XMM2_Bm",
        "XMM2_Bn",
        "XMM2_Bo",
        "XMM2_Bp",
        "XMM2_Da",
        "XMM2_Db",
        "XMM2_Dc",
        "XMM2_Dd",
        "XMM2_Qa",
        "XMM2_Qb",
        "XMM2_Wa",
        "XMM2_Wb",
        "XMM2_Wc",
        "XMM2_Wd",
        "XMM2_We",
        "XMM2_Wf",
        "XMM2_Wg",
        "XMM2_Wh",
        "YMM2",
        "YMM2_H",
    },
    "ZMM20": {
        "XMM20",
        "XMM20_Ba",
        "XMM20_Bb",
        "XMM20_Bc",
        "XMM20_Bd",
        "XMM20_Be",
        "XMM20_Bf",
        "XMM20_Bg",
        "XMM20_Bh",
        "XMM20_Bi",
        "XMM20_Bj",
        "XMM20_Bk",
        "XMM20_Bl",
        "XMM20_Bm",
        "XMM20_Bn",
        "XMM20_Bo",
        "XMM20_Bp",
        "XMM20_Da",
        "XMM20_Db",
        "XMM20_Dc",
        "XMM20_Dd",
        "XMM20_Qa",
        "XMM20_Qb",
        "XMM20_Wa",
        "XMM20_Wb",
        "XMM20_Wc",
        "XMM20_Wd",
        "XMM20_We",
        "XMM20_Wf",
        "XMM20_Wg",
        "XMM20_Wh",
        "YMM20",
        "YMM20_H",
    },
    "ZMM21": {
        "XMM21",
        "XMM21_Ba",
        "XMM21_Bb",
        "XMM21_Bc",
        "XMM21_Bd",
        "XMM21_Be",
        "XMM21_Bf",
        "XMM21_Bg",
        "XMM21_Bh",
        "XMM21_Bi",
        "XMM21_Bj",
        "XMM21_Bk",
        "XMM21_Bl",
        "XMM21_Bm",
        "XMM21_Bn",
        "XMM21_Bo",
        "XMM21_Bp",
        "XMM21_Da",
        "XMM21_Db",
        "XMM21_Dc",
        "XMM21_Dd",
        "XMM21_Qa",
        "XMM21_Qb",
        "XMM21_Wa",
        "XMM21_Wb",
        "XMM21_Wc",
        "XMM21_Wd",
        "XMM21_We",
        "XMM21_Wf",
        "XMM21_Wg",
        "XMM21_Wh",
        "YMM21",
        "YMM21_H",
    },
    "ZMM22": {
        "XMM22",
        "XMM22_Ba",
        "XMM22_Bb",
        "XMM22_Bc",
        "XMM22_Bd",
        "XMM22_Be",
        "XMM22_Bf",
        "XMM22_Bg",
        "XMM22_Bh",
        "XMM22_Bi",
        "XMM22_Bj",
        "XMM22_Bk",
        "XMM22_Bl",
        "XMM22_Bm",
        "XMM22_Bn",
        "XMM22_Bo",
        "XMM22_Bp",
        "XMM22_Da",
        "XMM22_Db",
        "XMM22_Dc",
        "XMM22_Dd",
        "XMM22_Qa",
        "XMM22_Qb",
        "XMM22_Wa",
        "XMM22_Wb",
        "XMM22_Wc",
        "XMM22_Wd",
        "XMM22_We",
        "XMM22_Wf",
        "XMM22_Wg",
        "XMM22_Wh",
        "YMM22",
        "YMM22_H",
    },
    "ZMM23": {
        "XMM23",
        "XMM23_Ba",
        "XMM23_Bb",
        "XMM23_Bc",
        "XMM23_Bd",
        "XMM23_Be",
        "XMM23_Bf",
        "XMM23_Bg",
        "XMM23_Bh",
        "XMM23_Bi",
        "XMM23_Bj",
        "XMM23_Bk",
        "XMM23_Bl",
        "XMM23_Bm",
        "XMM23_Bn",
        "XMM23_Bo",
        "XMM23_Bp",
        "XMM23_Da",
        "XMM23_Db",
        "XMM23_Dc",
        "XMM23_Dd",
        "XMM23_Qa",
        "XMM23_Qb",
        "XMM23_Wa",
        "XMM23_Wb",
        "XMM23_Wc",
        "XMM23_Wd",
        "XMM23_We",
        "XMM23_Wf",
        "XMM23_Wg",
        "XMM23_Wh",
        "YMM23",
        "YMM23_H",
    },
    "ZMM24": {
        "XMM24",
        "XMM24_Ba",
        "XMM24_Bb",
        "XMM24_Bc",
        "XMM24_Bd",
        "XMM24_Be",
        "XMM24_Bf",
        "XMM24_Bg",
        "XMM24_Bh",
        "XMM24_Bi",
        "XMM24_Bj",
        "XMM24_Bk",
        "XMM24_Bl",
        "XMM24_Bm",
        "XMM24_Bn",
        "XMM24_Bo",
        "XMM24_Bp",
        "XMM24_Da",
        "XMM24_Db",
        "XMM24_Dc",
        "XMM24_Dd",
        "XMM24_Qa",
        "XMM24_Qb",
        "XMM24_Wa",
        "XMM24_Wb",
        "XMM24_Wc",
        "XMM24_Wd",
        "XMM24_We",
        "XMM24_Wf",
        "XMM24_Wg",
        "XMM24_Wh",
        "YMM24",
        "YMM24_H",
    },
    "ZMM25": {
        "XMM25",
        "XMM25_Ba",
        "XMM25_Bb",
        "XMM25_Bc",
        "XMM25_Bd",
        "XMM25_Be",
        "XMM25_Bf",
        "XMM25_Bg",
        "XMM25_Bh",
        "XMM25_Bi",
        "XMM25_Bj",
        "XMM25_Bk",
        "XMM25_Bl",
        "XMM25_Bm",
        "XMM25_Bn",
        "XMM25_Bo",
        "XMM25_Bp",
        "XMM25_Da",
        "XMM25_Db",
        "XMM25_Dc",
        "XMM25_Dd",
        "XMM25_Qa",
        "XMM25_Qb",
        "XMM25_Wa",
        "XMM25_Wb",
        "XMM25_Wc",
        "XMM25_Wd",
        "XMM25_We",
        "XMM25_Wf",
        "XMM25_Wg",
        "XMM25_Wh",
        "YMM25",
        "YMM25_H",
    },
    "ZMM26": {
        "XMM26",
        "XMM26_Ba",
        "XMM26_Bb",
        "XMM26_Bc",
        "XMM26_Bd",
        "XMM26_Be",
        "XMM26_Bf",
        "XMM26_Bg",
        "XMM26_Bh",
        "XMM26_Bi",
        "XMM26_Bj",
        "XMM26_Bk",
        "XMM26_Bl",
        "XMM26_Bm",
        "XMM26_Bn",
        "XMM26_Bo",
        "XMM26_Bp",
        "XMM26_Da",
        "XMM26_Db",
        "XMM26_Dc",
        "XMM26_Dd",
        "XMM26_Qa",
        "XMM26_Qb",
        "XMM26_Wa",
        "XMM26_Wb",
        "XMM26_Wc",
        "XMM26_Wd",
        "XMM26_We",
        "XMM26_Wf",
        "XMM26_Wg",
        "XMM26_Wh",
        "YMM26",
        "YMM26_H",
    },
    "ZMM27": {
        "XMM27",
        "XMM27_Ba",
        "XMM27_Bb",
        "XMM27_Bc",
        "XMM27_Bd",
        "XMM27_Be",
        "XMM27_Bf",
        "XMM27_Bg",
        "XMM27_Bh",
        "XMM27_Bi",
        "XMM27_Bj",
        "XMM27_Bk",
        "XMM27_Bl",
        "XMM27_Bm",
        "XMM27_Bn",
        "XMM27_Bo",
        "XMM27_Bp",
        "XMM27_Da",
        "XMM27_Db",
        "XMM27_Dc",
        "XMM27_Dd",
        "XMM27_Qa",
        "XMM27_Qb",
        "XMM27_Wa",
        "XMM27_Wb",
        "XMM27_Wc",
        "XMM27_Wd",
        "XMM27_We",
        "XMM27_Wf",
        "XMM27_Wg",
        "XMM27_Wh",
        "YMM27",
        "YMM27_H",
    },
    "ZMM28": {
        "XMM28",
        "XMM28_Ba",
        "XMM28_Bb",
        "XMM28_Bc",
        "XMM28_Bd",
        "XMM28_Be",
        "XMM28_Bf",
        "XMM28_Bg",
        "XMM28_Bh",
        "XMM28_Bi",
        "XMM28_Bj",
        "XMM28_Bk",
        "XMM28_Bl",
        "XMM28_Bm",
        "XMM28_Bn",
        "XMM28_Bo",
        "XMM28_Bp",
        "XMM28_Da",
        "XMM28_Db",
        "XMM28_Dc",
        "XMM28_Dd",
        "XMM28_Qa",
        "XMM28_Qb",
        "XMM28_Wa",
        "XMM28_Wb",
        "XMM28_Wc",
        "XMM28_Wd",
        "XMM28_We",
        "XMM28_Wf",
        "XMM28_Wg",
        "XMM28_Wh",
        "YMM28",
        "YMM28_H",
    },
    "ZMM29": {
        "XMM29",
        "XMM29_Ba",
        "XMM29_Bb",
        "XMM29_Bc",
        "XMM29_Bd",
        "XMM29_Be",
        "XMM29_Bf",
        "XMM29_Bg",
        "XMM29_Bh",
        "XMM29_Bi",
        "XMM29_Bj",
        "XMM29_Bk",
        "XMM29_Bl",
        "XMM29_Bm",
        "XMM29_Bn",
        "XMM29_Bo",
        "XMM29_Bp",
        "XMM29_Da",
        "XMM29_Db",
        "XMM29_Dc",
        "XMM29_Dd",
        "XMM29_Qa",
        "XMM29_Qb",
        "XMM29_Wa",
        "XMM29_Wb",
        "XMM29_Wc",
        "XMM29_Wd",
        "XMM29_We",
        "XMM29_Wf",
        "XMM29_Wg",
        "XMM29_Wh",
        "YMM29",
        "YMM29_H",
    },
    "ZMM3": {
        "XMM3",
        "XMM3_Ba",
        "XMM3_Bb",
        "XMM3_Bc",
        "XMM3_Bd",
        "XMM3_Be",
        "XMM3_Bf",
        "XMM3_Bg",
        "XMM3_Bh",
        "XMM3_Bi",
        "XMM3_Bj",
        "XMM3_Bk",
        "XMM3_Bl",
        "XMM3_Bm",
        "XMM3_Bn",
        "XMM3_Bo",
        "XMM3_Bp",
        "XMM3_Da",
        "XMM3_Db",
        "XMM3_Dc",
        "XMM3_Dd",
        "XMM3_Qa",
        "XMM3_Qb",
        "XMM3_Wa",
        "XMM3_Wb",
        "XMM3_Wc",
        "XMM3_Wd",
        "XMM3_We",
        "XMM3_Wf",
        "XMM3_Wg",
        "XMM3_Wh",
        "YMM3",
        "YMM3_H",
    },
    "ZMM30": {
        "XMM30",
        "XMM30_Ba",
        "XMM30_Bb",
        "XMM30_Bc",
        "XMM30_Bd",
        "XMM30_Be",
        "XMM30_Bf",
        "XMM30_Bg",
        "XMM30_Bh",
        "XMM30_Bi",
        "XMM30_Bj",
        "XMM30_Bk",
        "XMM30_Bl",
        "XMM30_Bm",
        "XMM30_Bn",
        "XMM30_Bo",
        "XMM30_Bp",
        "XMM30_Da",
        "XMM30_Db",
        "XMM30_Dc",
        "XMM30_Dd",
        "XMM30_Qa",
        "XMM30_Qb",
        "XMM30_Wa",
        "XMM30_Wb",
        "XMM30_Wc",
        "XMM30_Wd",
        "XMM30_We",
        "XMM30_Wf",
        "XMM30_Wg",
        "XMM30_Wh",
        "YMM30",
        "YMM30_H",
    },
    "ZMM31": {
        "XMM31",
        "XMM31_Ba",
        "XMM31_Bb",
        "XMM31_Bc",
        "XMM31_Bd",
        "XMM31_Be",
        "XMM31_Bf",
        "XMM31_Bg",
        "XMM31_Bh",
        "XMM31_Bi",
        "XMM31_Bj",
        "XMM31_Bk",
        "XMM31_Bl",
        "XMM31_Bm",
        "XMM31_Bn",
        "XMM31_Bo",
        "XMM31_Bp",
        "XMM31_Da",
        "XMM31_Db",
        "XMM31_Dc",
        "XMM31_Dd",
        "XMM31_Qa",
        "XMM31_Qb",
        "XMM31_Wa",
        "XMM31_Wb",
        "XMM31_Wc",
        "XMM31_Wd",
        "XMM31_We",
        "XMM31_Wf",
        "XMM31_Wg",
        "XMM31_Wh",
        "YMM31",
        "YMM31_H",
    },
    "ZMM4": {
        "XMM4",
        "XMM4_Ba",
        "XMM4_Bb",
        "XMM4_Bc",
        "XMM4_Bd",
        "XMM4_Be",
        "XMM4_Bf",
        "XMM4_Bg",
        "XMM4_Bh",
        "XMM4_Bi",
        "XMM4_Bj",
        "XMM4_Bk",
        "XMM4_Bl",
        "XMM4_Bm",
        "XMM4_Bn",
        "XMM4_Bo",
        "XMM4_Bp",
        "XMM4_Da",
        "XMM4_Db",
        "XMM4_Dc",
        "XMM4_Dd",
        "XMM4_Qa",
        "XMM4_Qb",
        "XMM4_Wa",
        "XMM4_Wb",
        "XMM4_Wc",
        "XMM4_Wd",
        "XMM4_We",
        "XMM4_Wf",
        "XMM4_Wg",
        "XMM4_Wh",
        "YMM4",
        "YMM4_H",
    },
    "ZMM5": {
        "XMM5",
        "XMM5_Ba",
        "XMM5_Bb",
        "XMM5_Bc",
        "XMM5_Bd",
        "XMM5_Be",
        "XMM5_Bf",
        "XMM5_Bg",
        "XMM5_Bh",
        "XMM5_Bi",
        "XMM5_Bj",
        "XMM5_Bk",
        "XMM5_Bl",
        "XMM5_Bm",
        "XMM5_Bn",
        "XMM5_Bo",
        "XMM5_Bp",
        "XMM5_Da",
        "XMM5_Db",
        "XMM5_Dc",
        "XMM5_Dd",
        "XMM5_Qa",
        "XMM5_Qb",
        "XMM5_Wa",
        "XMM5_Wb",
        "XMM5_Wc",
        "XMM5_Wd",
        "XMM5_We",
        "XMM5_Wf",
        "XMM5_Wg",
        "XMM5_Wh",
        "YMM5",
        "YMM5_H",
    },
    "ZMM6": {
        "XMM6",
        "XMM6_Ba",
        "XMM6_Bb",
        "XMM6_Bc",
        "XMM6_Bd",
        "XMM6_Be",
        "XMM6_Bf",
        "XMM6_Bg",
        "XMM6_Bh",
        "XMM6_Bi",
        "XMM6_Bj",
        "XMM6_Bk",
        "XMM6_Bl",
        "XMM6_Bm",
        "XMM6_Bn",
        "XMM6_Bo",
        "XMM6_Bp",
        "XMM6_Da",
        "XMM6_Db",
        "XMM6_Dc",
        "XMM6_Dd",
        "XMM6_Qa",
        "XMM6_Qb",
        "XMM6_Wa",
        "XMM6_Wb",
        "XMM6_Wc",
        "XMM6_Wd",
        "XMM6_We",
        "XMM6_Wf",
        "XMM6_Wg",
        "XMM6_Wh",
        "YMM6",
        "YMM6_H",
    },
    "ZMM7": {
        "XMM7",
        "XMM7_Ba",
        "XMM7_Bb",
        "XMM7_Bc",
        "XMM7_Bd",
        "XMM7_Be",
        "XMM7_Bf",
        "XMM7_Bg",
        "XMM7_Bh",
        "XMM7_Bi",
        "XMM7_Bj",
        "XMM7_Bk",
        "XMM7_Bl",
        "XMM7_Bm",
        "XMM7_Bn",
        "XMM7_Bo",
        "XMM7_Bp",
        "XMM7_Da",
        "XMM7_Db",
        "XMM7_Dc",
        "XMM7_Dd",
        "XMM7_Qa",
        "XMM7_Qb",
        "XMM7_Wa",
        "XMM7_Wb",
        "XMM7_Wc",
        "XMM7_Wd",
        "XMM7_We",
        "XMM7_Wf",
        "XMM7_Wg",
        "XMM7_Wh",
        "YMM7",
        "YMM7_H",
    },
    "ZMM8": {
        "XMM8",
        "XMM8_Ba",
        "XMM8_Bb",
        "XMM8_Bc",
        "XMM8_Bd",
        "XMM8_Be",
        "XMM8_Bf",
        "XMM8_Bg",
        "XMM8_Bh",
        "XMM8_Bi",
        "XMM8_Bj",
        "XMM8_Bk",
        "XMM8_Bl",
        "XMM8_Bm",
        "XMM8_Bn",
        "XMM8_Bo",
        "XMM8_Bp",
        "XMM8_Da",
        "XMM8_Db",
        "XMM8_Dc",
        "XMM8_Dd",
        "XMM8_Qa",
        "XMM8_Qb",
        "XMM8_Wa",
        "XMM8_Wb",
        "XMM8_Wc",
        "XMM8_Wd",
        "XMM8_We",
        "XMM8_Wf",
        "XMM8_Wg",
        "XMM8_Wh",
        "YMM8",
        "YMM8_H",
    },
    "ZMM9": {
        "XMM9",
        "XMM9_Ba",
        "XMM9_Bb",
        "XMM9_Bc",
        "XMM9_Bd",
        "XMM9_Be",
        "XMM9_Bf",
        "XMM9_Bg",
        "XMM9_Bh",
        "XMM9_Bi",
        "XMM9_Bj",
        "XMM9_Bk",
        "XMM9_Bl",
        "XMM9_Bm",
        "XMM9_Bn",
        "XMM9_Bo",
        "XMM9_Bp",
        "XMM9_Da",
        "XMM9_Db",
        "XMM9_Dc",
        "XMM9_Dd",
        "XMM9_Qa",
        "XMM9_Qb",
        "XMM9_Wa",
        "XMM9_Wb",
        "XMM9_Wc",
        "XMM9_Wd",
        "XMM9_We",
        "XMM9_Wf",
        "XMM9_Wg",
        "XMM9_Wh",
        "YMM9",
        "YMM9_H",
    },
    "ZmmMask": {"XmmMask", "YmmMask"},
    "ZmmResult": {"XmmResult", "YmmResult"},
    "rflags": {"eflags", "flags"},
    "xmmTmp1": {
        "xmmTmp1_Da",
        "xmmTmp1_Db",
        "xmmTmp1_Dc",
        "xmmTmp1_Dd",
        "xmmTmp1_Qa",
        "xmmTmp1_Qb",
    },
    "xmmTmp2": {
        "xmmTmp2_Da",
        "xmmTmp2_Db",
        "xmmTmp2_Dc",
        "xmmTmp2_Dd",
        "xmmTmp2_Qa",
        "xmmTmp2_Qb",
    },
}

# arm_32 -- ARM:LE:32:v8 (17 groupes)
ALIAS[Arch.arm_32] = {
    "mult_dat16": {"mult_dat8"},
    "q0": {"d0", "d1", "s0", "s1", "s2", "s3"},
    "q1": {"d2", "d3", "s4", "s5", "s6", "s7"},
    "q10": {"d20", "d21"},
    "q11": {"d22", "d23"},
    "q12": {"d24", "d25"},
    "q13": {"d26", "d27"},
    "q14": {"d28", "d29"},
    "q15": {"d30", "d31"},
    "q2": {"d4", "d5", "s10", "s11", "s8", "s9"},
    "q3": {"d6", "d7", "s12", "s13", "s14", "s15"},
    "q4": {"d8", "d9", "s16", "s17", "s18", "s19"},
    "q5": {"d10", "d11", "s20", "s21", "s22", "s23"},
    "q6": {"d12", "d13", "s24", "s25", "s26", "s27"},
    "q7": {"d14", "d15", "s28", "s29", "s30", "s31"},
    "q8": {"d16", "d17"},
    "q9": {"d18", "d19"},
}

# arm_64 -- AARCH64:LE:64:v8A (72 groupes)
ALIAS[Arch.arm_64] = {
    "TMPZ1": {"TMPD1", "TMPQ1", "TMPS1"},
    "TMPZ2": {"TMPD2", "TMPQ2", "TMPS2"},
    "TMPZ3": {"TMPD3", "TMPQ3", "TMPS3"},
    "TMPZ4": {"TMPD4", "TMPQ4", "TMPS4"},
    "TMPZ5": {"TMPD5", "TMPQ5", "TMPS5"},
    "TMPZ6": {"TMPD6", "TMPQ6", "TMPS6"},
    "gcr_el1": {"gcr_el1.exclude"},
    "sp": {"wsp"},
    "x0": {"w0"},
    "x1": {"w1"},
    "x10": {"w10"},
    "x11": {"w11"},
    "x12": {"w12"},
    "x13": {"w13"},
    "x14": {"w14"},
    "x15": {"w15"},
    "x16": {"w16"},
    "x17": {"w17"},
    "x18": {"w18"},
    "x19": {"w19"},
    "x2": {"w2"},
    "x20": {"w20"},
    "x21": {"w21"},
    "x22": {"w22"},
    "x23": {"w23"},
    "x24": {"w24"},
    "x25": {"w25"},
    "x26": {"w26"},
    "x27": {"w27"},
    "x28": {"w28"},
    "x29": {"w29"},
    "x3": {"w3"},
    "x30": {"w30"},
    "x4": {"w4"},
    "x5": {"w5"},
    "x6": {"w6"},
    "x7": {"w7"},
    "x8": {"w8"},
    "x9": {"w9"},
    "xzr": {"wzr"},
    "z0": {"b0", "d0", "h0", "q0", "s0"},
    "z1": {"b1", "d1", "h1", "q1", "s1"},
    "z10": {"b10", "d10", "h10", "q10", "s10"},
    "z11": {"b11", "d11", "h11", "q11", "s11"},
    "z12": {"b12", "d12", "h12", "q12", "s12"},
    "z13": {"b13", "d13", "h13", "q13", "s13"},
    "z14": {"b14", "d14", "h14", "q14", "s14"},
    "z15": {"b15", "d15", "h15", "q15", "s15"},
    "z16": {"b16", "d16", "h16", "q16", "s16"},
    "z17": {"b17", "d17", "h17", "q17", "s17"},
    "z18": {"b18", "d18", "h18", "q18", "s18"},
    "z19": {"b19", "d19", "h19", "q19", "s19"},
    "z2": {"b2", "d2", "h2", "q2", "s2"},
    "z20": {"b20", "d20", "h20", "q20", "s20"},
    "z21": {"b21", "d21", "h21", "q21", "s21"},
    "z22": {"b22", "d22", "h22", "q22", "s22"},
    "z23": {"b23", "d23", "h23", "q23", "s23"},
    "z24": {"b24", "d24", "h24", "q24", "s24"},
    "z25": {"b25", "d25", "h25", "q25", "s25"},
    "z26": {"b26", "d26", "h26", "q26", "s26"},
    "z27": {"b27", "d27", "h27", "q27", "s27"},
    "z28": {"b28", "d28", "h28", "q28", "s28"},
    "z29": {"b29", "d29", "h29", "q29", "s29"},
    "z3": {"b3", "d3", "h3", "q3", "s3"},
    "z30": {"b30", "d30", "h30", "q30", "s30"},
    "z31": {"b31", "d31", "h31", "q31", "s31"},
    "z4": {"b4", "d4", "h4", "q4", "s4"},
    "z5": {"b5", "d5", "h5", "q5", "s5"},
    "z6": {"b6", "d6", "h6", "q6", "s6"},
    "z7": {"b7", "d7", "h7", "q7", "s7"},
    "z8": {"b8", "d8", "h8", "q8", "s8"},
    "z9": {"b9", "d9", "h9", "q9", "s9"},
}

# mips_32 -- MIPS:BE:32:default (20 groupes)
ALIAS[Arch.mips_32] = {
    "ac0": {"hi", "lo"},
    "ac1": {"hi1", "lo1"},
    "ac2": {"hi2", "lo2"},
    "ac3": {"hi3", "lo3"},
    "f0_1": {"f0", "f1"},
    "f10_11": {"f10", "f11"},
    "f12_13": {"f12", "f13"},
    "f14_15": {"f14", "f15"},
    "f16_17": {"f16", "f17"},
    "f18_19": {"f18", "f19"},
    "f20_21": {"f20", "f21"},
    "f22_23": {"f22", "f23"},
    "f24_25": {"f24", "f25"},
    "f26_27": {"f26", "f27"},
    "f28_29": {"f28", "f29"},
    "f2_3": {"f2", "f3"},
    "f30_31": {"f30", "f31"},
    "f4_5": {"f4", "f5"},
    "f6_7": {"f6", "f7"},
    "f8_9": {"f8", "f9"},
}

# mips_64 -- MIPS:BE:64:default (37 groupes)
ALIAS[Arch.mips_64] = {
    "a0": {"a0_hi", "a0_lo"},
    "a1": {"a1_hi", "a1_lo"},
    "a2": {"a2_hi", "a2_lo"},
    "a3": {"a3_hi", "a3_lo"},
    "ac0": {"hi", "lo"},
    "ac1": {"hi1", "lo1"},
    "ac2": {"hi2", "lo2"},
    "ac3": {"hi3", "lo3"},
    "at": {"at_hi", "at_lo"},
    "gp": {"gp_hi", "gp_lo"},
    "k0": {"k0_hi", "k0_lo"},
    "k1": {"k1_hi", "k1_lo"},
    "pc": {"pc_hi", "pc_lo"},
    "ra": {"ra_hi", "ra_lo"},
    "s0": {"s0_hi", "s0_lo"},
    "s1": {"s1_hi", "s1_lo"},
    "s2": {"s2_hi", "s2_lo"},
    "s3": {"s3_hi", "s3_lo"},
    "s4": {"s4_hi", "s4_lo"},
    "s5": {"s5_hi", "s5_lo"},
    "s6": {"s6_hi", "s6_lo"},
    "s7": {"s7_hi", "s7_lo"},
    "s8": {"s8_hi", "s8_lo"},
    "sp": {"sp_hi", "sp_lo"},
    "t0": {"t0_hi", "t0_lo"},
    "t1": {"t1_hi", "t1_lo"},
    "t2": {"t2_hi", "t2_lo"},
    "t3": {"t3_hi", "t3_lo"},
    "t4": {"t4_hi", "t4_lo"},
    "t5": {"t5_hi", "t5_lo"},
    "t6": {"t6_hi", "t6_lo"},
    "t7": {"t7_hi", "t7_lo"},
    "t8": {"t8_hi", "t8_lo"},
    "t9": {"t9_hi", "t9_lo"},
    "v0": {"v0_hi", "v0_lo"},
    "v1": {"v1_hi", "v1_lo"},
    "zero": {"zero_hi", "zero_lo"},
}


PARENTS: dict[Arch, dict[str, str]] = {}

for _arch, _group in ALIAS.items():
    for _parent, _children in _group.items():
        _parents_dict = PARENTS.setdefault(_arch, {})
        for _child in _children:
            _parents_dict[_child] = _parent


# List of registers that we can safely ignore writes
# when building the graph (depending on your use case.)
SPECIAL_REGISTERS: dict[Arch, set[str]] = {
    Arch.x86_64: {
        "AC",
        "CF",
        "ID",
        "IF",
        "NT",
        "OF",
        "PF",
        "RIP",
        "RSP",
        "SF",
        "TF",
        "ZF",
    },
    Arch.x86_32: {
        "AC",
        "CF",
        "EIP",
        "ESP",
        "ID",
        "IF",
        "NT",
        "OF",
        "PF",
        "SF",
        "TF",
        "ZF",
    },
    Arch.arm_64: {
        "CY",
        "NG",
        "OV",
        "pc",
        "sp",
        "ZR",
    },
    Arch.arm_32: {
        "CY",
        "ISAModeSwitch",
        "lr",
        "mult_addr",
        "NG",
        "OV",
        "pc",
        "shift_carry",
        "sp",
        "TB",
        "ZR",
    },
    Arch.mips_32: {
        "at",
        "fcsr",
        "fp",
        "gp",
        "hi",
        "k0",
        "k1",
        "lo",
        "ra",
        "s8",
        "sp",
        "zero",
    },
    Arch.mips_64: {
        "at",
        "fcsr",
        "fp",
        "gp",
        "hi",
        "k0",
        "k1",
        "lo",
        "ra",
        "s8",
        "sp",
        "zero",
    },
}


# Linux calling conventions (System V / AAPCS / O32-N64) -- argument and return
# registers only. List order = argument assignment order. Stack spilling is not
# covered here.

CALLING_CONVENTIONS: dict[Arch, dict[str, list[str]]] = {
    Arch.x86_32: {
        "return": ["eax"],
        "return_64": ["edx"],
        "return_fp": ["st0"],
    },
    Arch.x86_64: {
        "return": ["rax"],
        "return_128": ["rdx"],
        "return_fp": ["xmm0", "xmm1"],
        "args_int": ["rdi", "rsi", "rdx", "rcx", "r8", "r9"],
        "args_fp": ["xmm0", "xmm1", "xmm2", "xmm3", "xmm4", "xmm5", "xmm6", "xmm7"],
    },
    Arch.arm_32: {
        "return": ["r0"],
        "return_64": ["r1"],
        "return_dp": ["d0"],
        "args_int": ["r0", "r1", "r2", "r3"],
        "args_fp": ["d0", "d1", "d2", "d3", "d4", "d5", "d6", "d7"],
    },
    Arch.arm_64: {
        "return": ["x0"],
        "return_128": ["x1"],
        "return_fp": ["d0", "d1", "d2", "d3"],
        "args_int": ["x0", "x1", "x2", "x3", "x4", "x5", "x6", "x7"],
        "args_fp": ["d0", "d1", "d2", "d3", "d4", "d5", "d6", "d7"],
    },
    Arch.mips_32: {
        "return": ["v0"],
        "return_64": ["v1"],
        "return_fp": ["f0", "f2"],
        "args_int": ["a0", "a1", "a2", "a3"],
        "args_fp": ["f12", "f14"],
    },
    Arch.mips_64: {
        "return": ["v0"],
        "return_128": ["v1"],
        "return_fp": ["f0", "f2"],
        "args_int": ["a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7"],
        "args_fp": ["f12", "f13", "f14", "f15", "f16", "f17", "f18", "f19"],
    },
}
